# ----
# Site

title: HRC Model Set
url: "https://scazlab.github.io/HRC-model-set/"
baseurl: "/HRC-model-set"
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /scazlablogo.png
description: Documentation for the Human-Robot Collaboration Model Set
author:
  name: Sofya Zeylikman, Sarah Widder, Alessandro Roncone , Olivier Mangin and Brian Scassellati
  email:
  twitter: # twitter username without the @ symbol
social:
  name:
  links:
    - https://github.com/ScazLab/HRC-model-set

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
